services:
  app:
    build: .
    tty: true
    volumes:
    - .:/code

  mlflow:
    image: ghcr.io/mlflow/mlflow
    tty: true
    ports:
      - "5050:5050"
    volumes:
      - ./mlruns:/mlruns
    command: mlflow server --host 0.0.0.0 --port 5050